const RGBA_LOOKUP_SIZE = 200;

// create a lookup table for indices generated by findDbzIndexGenerator
const findDbzRbgaGenerator = (limits, palette) => {
	const lookupRgba = [];
	for (let i = 0; i < palette.length; i += 4) {
		lookupRgba.push(`rgba(${palette[i]},${palette[i + 1]},${palette[i + 2]},${palette[(i + 3)] / 255})`);
	}
	return lookupRgba;
};

// create a lookup table of colors by palette index
const findDbzIndexGenerator = (limits, palette, maxDbzIndex = 14) => {
	const lookupRgba = [];
	for (let i = -RGBA_LOOKUP_SIZE; i <= RGBA_LOOKUP_SIZE; i += 1) {
		let index = limits.findIndex((limit) => i < limit);
		// a value of -1 means it is off the end of the scale, set to highest value
		if (index === -1) index = maxDbzIndex;
		lookupRgba.push(index);
	}
	return lookupRgba;
};

const downSample = (cur, prev) => (cur === null ? prev : Math.max(cur, prev));

const inDeadband = (reset) => (a) => (a === null || a === reset || a === undefined);

export {
	findDbzIndexGenerator,
	findDbzRbgaGenerator,
	downSample,
	inDeadband,
	RGBA_LOOKUP_SIZE,
};
